project:
  type: website
  output-dir: docs

website:
  title: "Daniela! "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cookingwithdani.qmd
      - resume.qmd

format:
  html:
    theme: Minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

